#!/usr/bin/env bash

# load .env file
if [[ -f .env ]]; then
    source .env
fi

# set variables MAILING_VERSION and MAILING_CORE_VERSION to the value of the "version" attribute from each package.json
MAILING_VERSION=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' packages/cli/package.json)
MAILING_CORE_VERSION=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' packages/core/package.json)

# throw an error if $MAILING_VERSION is empty
if [[ -z "$MAILING_VERSION" ]]; then
    echo "Failed to set MAILING_VERSION" 1>&2
    exit 1
fi

# throw an error if $MAILING_CORE_VERSION is empty
if [[ -z "$MAILING_CORE_VERSION" ]]; then
    echo "Must provide MAILING_CORE_VERSION in environment" 1>&2
    exit 1
fi

##
# Search and replace in src directories

## build packages only, without publishing
pnpm run build

## create a local tarball of each package
mkdir -p dist
pnpm --filter @catloafsoft/mailing exec npm pack --pack-destination ../../dist --silent
mv dist/catloafsoft-mailing-$MAILING_VERSION.tgz dist/catloafsoft-mailing-v$MAILING_VERSION.tgz
pnpm --filter @catloafsoft/mailing-core exec npm pack --pack-destination ../../dist --silent
mv dist/catloafsoft-mailing-core-$MAILING_CORE_VERSION.tgz dist/catloafsoft-mailing-core-v$MAILING_CORE_VERSION.tgz

echo "Created packages in dist/ directory:"
ls -la dist/
