name: Rubocop
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
